"""initial market forecaster schema

Revision ID: 7014147e9da6
Revises: 
Create Date: 2026-03-26 20:29:19.036827
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7014147e9da6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_label', sa.String(length=120), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=12), nullable=False),
    sa.Column('universe_version', sa.String(length=24), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('average_return', sa.Float(), nullable=False),
    sa.Column('benchmark_return', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('calibration_error', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_runs_generated_at', 'backtest_runs', ['generated_at'], unique=False)
    op.create_table('connector_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_name', sa.String(length=40), nullable=False),
    sa.Column('last_cursor', sa.String(length=255), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_name', name='uq_connector_states_name')
    )
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=60), nullable=False),
    sa.Column('exchange', sa.String(length=24), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('day_change_pct', sa.Float(), nullable=False),
    sa.Column('last_price_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_securities_symbol')
    )
    op.create_index('ix_securities_is_active', 'securities', ['is_active'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('headline', sa.String(length=280), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_source_snapshots_content_hash')
    )
    op.create_index('ix_source_snapshots_published_at', 'source_snapshots', ['published_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=120), nullable=True),
    sa.Column('password_reset_token', sa.String(length=120), nullable=True),
    sa.Column('disclosures_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_events_action', 'activity_events', ['action'], unique=False)
    op.create_index('ix_activity_events_created_at', 'activity_events', ['created_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('headline', sa.String(length=280), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('source_label', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('directional_bias', sa.Float(), nullable=False),
    sa.Column('is_material', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('operator_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_events_dedupe_key')
    )
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_occurred_at', 'events', ['occurred_at'], unique=False)
    op.create_index('ix_events_security_id', 'events', ['security_id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('allocation_pct', sa.Float(), nullable=False),
    sa.Column('model_action', sa.String(length=12), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_positions_status', 'portfolio_positions', ['status'], unique=False)
    op.create_index('ix_portfolio_positions_user_id', 'portfolio_positions', ['user_id'], unique=False)
    op.create_table('subscription_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=120), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('last_webhook_event_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_subscription_states_user_id')
    )
    op.create_index('ix_subscription_states_status', 'subscription_states', ['status'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('age_band', sa.String(length=32), nullable=False),
    sa.Column('investable_amount_band', sa.String(length=32), nullable=False),
    sa.Column('goal_primary', sa.String(length=40), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=24), nullable=False),
    sa.Column('max_drawdown_band', sa.String(length=24), nullable=False),
    sa.Column('holding_period_preference', sa.String(length=32), nullable=False),
    sa.Column('income_stability_band', sa.String(length=24), nullable=False),
    sa.Column('sector_concentration_tolerance', sa.String(length=24), nullable=False),
    sa.Column('experience_level', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlists_user_id', 'watchlists', ['user_id'], unique=False)
    op.create_table('recommendation_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('latest_event_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('conviction_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('analog_sample_size', sa.Integer(), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=12), nullable=False),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('thesis_summary', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('invalidation_conditions', sa.Text(), nullable=False),
    sa.Column('factor_scores', sa.JSON(), nullable=False),
    sa.Column('horizon_ranges', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['latest_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_snapshots_generated_at', 'recommendation_snapshots', ['generated_at'], unique=False)
    op.create_index('ix_recommendation_snapshots_security_id', 'recommendation_snapshots', ['security_id'], unique=False)
    op.create_table('watchlist_securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'security_id', name='uq_watchlist_security')
    )
    op.create_index('ix_watchlist_securities_security_id', 'watchlist_securities', ['security_id'], unique=False)
    op.create_table('user_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('conviction_score', sa.Integer(), nullable=False),
    sa.Column('profile_fit_score', sa.Float(), nullable=False),
    sa.Column('allocation_min_pct', sa.Float(), nullable=False),
    sa.Column('allocation_max_pct', sa.Float(), nullable=False),
    sa.Column('urgency_label', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('profile_inputs_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_snapshot_id'], ['recommendation_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recommendation_snapshot_id', name='uq_user_recommendation_snapshot')
    )
    op.create_index('ix_user_recommendations_action', 'user_recommendations', ['action'], unique=False)
    op.create_index('ix_user_recommendations_user_id', 'user_recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_recommendations_user_id', table_name='user_recommendations')
    op.drop_index('ix_user_recommendations_action', table_name='user_recommendations')
    op.drop_table('user_recommendations')
    op.drop_index('ix_watchlist_securities_security_id', table_name='watchlist_securities')
    op.drop_table('watchlist_securities')
    op.drop_index('ix_recommendation_snapshots_security_id', table_name='recommendation_snapshots')
    op.drop_index('ix_recommendation_snapshots_generated_at', table_name='recommendation_snapshots')
    op.drop_table('recommendation_snapshots')
    op.drop_index('ix_watchlists_user_id', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_table('user_profiles')
    op.drop_index('ix_subscription_states_status', table_name='subscription_states')
    op.drop_table('subscription_states')
    op.drop_index('ix_portfolio_positions_user_id', table_name='portfolio_positions')
    op.drop_index('ix_portfolio_positions_status', table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index('ix_events_security_id', table_name='events')
    op.drop_index('ix_events_occurred_at', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_activity_events_created_at', table_name='activity_events')
    op.drop_index('ix_activity_events_action', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_source_snapshots_published_at', table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index('ix_securities_is_active', table_name='securities')
    op.drop_table('securities')
    op.drop_table('connector_states')
    op.drop_index('ix_backtest_runs_generated_at', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
