from __future__ import annotations

UNIVERSE_VERSION = "2026-03"
BENCHMARK_SYMBOL = "QQQ"

UNIVERSE_SECURITIES: list[dict[str, str]] = [
    {"symbol": "AAPL", "company_name": "Apple", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000320193"},
    {"symbol": "MSFT", "company_name": "Microsoft", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000789019"},
    {"symbol": "NVDA", "company_name": "NVIDIA", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0001045810"},
    {"symbol": "AVGO", "company_name": "Broadcom", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0001730168"},
    {"symbol": "META", "company_name": "Meta Platforms", "sector": "Communication Services", "exchange": "NASDAQ", "cik": "0001326801"},
    {"symbol": "GOOGL", "company_name": "Alphabet", "sector": "Communication Services", "exchange": "NASDAQ", "cik": "0001652044"},
    {"symbol": "AMZN", "company_name": "Amazon", "sector": "Consumer Discretionary", "exchange": "NASDAQ", "cik": "0001018724"},
    {"symbol": "TSLA", "company_name": "Tesla", "sector": "Consumer Discretionary", "exchange": "NASDAQ", "cik": "0001318605"},
    {"symbol": "NFLX", "company_name": "Netflix", "sector": "Communication Services", "exchange": "NASDAQ", "cik": "0001065280"},
    {"symbol": "AMD", "company_name": "Advanced Micro Devices", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000002488"},
    {"symbol": "QCOM", "company_name": "Qualcomm", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000804328"},
    {"symbol": "AMAT", "company_name": "Applied Materials", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000006951"},
    {"symbol": "ASML", "company_name": "ASML Holding", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000937966"},
    {"symbol": "MU", "company_name": "Micron Technology", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000723125"},
    {"symbol": "INTC", "company_name": "Intel", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000050863"},
    {"symbol": "ARM", "company_name": "Arm Holdings", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0001973239"},
    {"symbol": "TSM", "company_name": "Taiwan Semiconductor Manufacturing", "sector": "Information Technology", "exchange": "NYSE", "cik": "0001046179"},
    {"symbol": "MRVL", "company_name": "Marvell Technology", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0001835632"},
    {"symbol": "ADI", "company_name": "Analog Devices", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000006281"},
    {"symbol": "NXPI", "company_name": "NXP Semiconductors", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0001413447"},
    {"symbol": "MCHP", "company_name": "Microchip Technology", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000827054"},
    {"symbol": "KLAC", "company_name": "KLA", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000319201"},
    {"symbol": "LRCX", "company_name": "Lam Research", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000707549"},
    {"symbol": "SNPS", "company_name": "Synopsys", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000883241"},
    {"symbol": "CDNS", "company_name": "Cadence Design Systems", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000813672"},
    {"symbol": "ADBE", "company_name": "Adobe", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0000796343"},
    {"symbol": "CRM", "company_name": "Salesforce", "sector": "Information Technology", "exchange": "NYSE", "cik": "0001108524"},
    {"symbol": "ORCL", "company_name": "Oracle", "sector": "Information Technology", "exchange": "NYSE", "cik": "0001341439"},
    {"symbol": "PANW", "company_name": "Palo Alto Networks", "sector": "Information Technology", "exchange": "NASDAQ", "cik": "0001327567"},
    {"symbol": "NOW", "company_name": "ServiceNow", "sector": "Information Technology", "exchange": "NYSE", "cik": "0001373715"},
]

SAMPLE_PRICE_MAP: dict[str, float] = {
    "QQQ": 488.12,
    "AAPL": 224.18,
    "MSFT": 431.09,
    "NVDA": 1187.44,
    "AVGO": 1732.88,
    "META": 523.94,
    "GOOGL": 182.15,
    "AMZN": 188.24,
    "TSLA": 184.36,
    "NFLX": 662.18,
    "AMD": 184.63,
    "QCOM": 175.52,
    "AMAT": 221.94,
    "ASML": 972.13,
    "MU": 124.12,
    "INTC": 41.81,
    "ARM": 138.42,
    "TSM": 161.13,
    "MRVL": 81.07,
    "ADI": 211.49,
    "NXPI": 254.33,
    "MCHP": 94.28,
    "KLAC": 723.84,
    "LRCX": 995.26,
    "SNPS": 563.44,
    "CDNS": 307.88,
    "ADBE": 497.18,
    "CRM": 306.58,
    "ORCL": 141.37,
    "PANW": 322.07,
    "NOW": 783.29,
}
